#!/bin/bash

# check
c:
  bun --bun run check

# test
t:
  bun run test

d:
  MODE=DEV bun --bun run dev || mk docs

docs:
  DEV=true bun scripts/docs.ts

# Test build
b:
  MODE=TEST bun run build --mode test && \
    mk docs

# Production build
build:
  bun run build && \
    mk docs

pack:
  docker run -it --rm --entrypoint "" \
    -v $(pwd):/usr/src/app \
    -v $HOME/Sync/web-maid/key.pem:/usr/src/key.pem \
    zenika/alpine-chrome chromium-browser --no-sandbox \
    --pack-extension=/usr/src/app/dist --pack-extension-key=/usr/src/key.pem

tag:
  mv dist.crx web-maid-$(jq -r .version package.json).crx

release:
  mk build && mk pack && mk tag
