#!/bin/bash

# check
c:
  bun --bun run check

# dev
d: docs
  MODE=DEV bun --bun run dev

# test
t:
  bun run test

# Test build
b: docs
  MODE=TEST bun run build --mode test

# Production build
build: docs
  bun run build

docs:
  DEV=true bun scripts/docs.ts

pack:
  docker run -it --rm --entrypoint "" \
    -v $(pwd):/usr/src/app \
    -v $HOME/Sync/web-maid/key.pem:/usr/src/key.pem \
    zenika/alpine-chrome chromium-browser --no-sandbox \
    --pack-extension=/usr/src/app/dist --pack-extension-key=/usr/src/key.pem

pack2:
  $BROWSER --pack-extension=dist --pack-extension-key=$HOME/Sync/web-maid/key.pem

tag:
  mv dist.crx web-maid-$(jq -r .version package.json).crx

release: build pack2 tag
